export const mock_wishlist =   [
    {
      id: "wish1",
      userId: "user1",
      userName: "John Doe",
      userEmail: "john@example.com",
      itemCount: 5,
      lastUpdated: "2023-06-10T14:45:00Z",
    },
    {
      id: "wish2",
      userId: "user2",
      userName: "Jane Smith",
      userEmail: "jane@example.com",
      itemCount: 3,
      lastUpdated: "2023-06-12T09:30:00Z",
    },
    {
      id: "wish3",
      userId: "user3",
      userName: "Robert Johnson",
      userEmail: "robert@example.com",
      itemCount: 7,
      lastUpdated: "2023-06-13T11:20:00Z",
    },
    {
      id: "wish4",
      userId: "user4",
      userName: "Emily Davis",
      userEmail: "emily@example.com",
      itemCount: 2,
      lastUpdated: "2023-06-14T08:15:00Z",
    },
    {
      id: "wish5",
      userId: "user5",
      userName: "Michael Wilson",
      userEmail: "michael@example.com",
      itemCount: 4,
      lastUpdated: "2023-06-15T16:40:00Z",
    },
  ]